name: Demo
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.2+6

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  #localization
  easy_localization: ^3.0.1
  #check connection
  connectivity_plus: ^3.0.2
  #App Structure
  get: ^4.6.5
  # session
  shared_preferences: ^2.0.15
  #fonts google
  google_fonts: ^3.0.1
  #Text field
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0
  #slider
  carousel_slider: ^4.1.1
  #network image view
  cached_network_image: ^3.2.3
  #svg file view
  flutter_svg: ^1.1.6
  #responsive_sizer
  sizer: ^2.0.15
  #percentage indicator
  percent_indicator: ^4.2.2
  #gride for customize view
  flutter_staggered_grid_view: ^0.6.2
  #calendar
  table_calendar: ^3.0.8
  #slide to action
  flutter_slidable: ^2.0.0
  #Display chart
  syncfusion_flutter_charts: ^20.4.38
  #Rating bar
  flutter_rating_bar: ^4.0.1
  #api call
  dio: ^4.0.6
  #Video player youtube and vimeo and https url
  pod_player: ^0.1.0
  #jwt token generator
  jaguar_jwt: ^3.0.0
  #open url
  url_launcher: ^6.1.7
  #get current timezone name
  flutter_native_timezone: ^2.0.0
  #to view app in all device and os
  device_preview: ^1.1.0
  #pdf view in app
  syncfusion_flutter_pdfviewer: ^20.4.44
  #audio play
  just_audio: any
  #audio progressbar
  audio_video_progress_bar: ^0.11.0
  #path provider to store pdf
  path_provider: ^2.0.7
  #permission taker
  permission_handler: ^8.1.4+2
  #Display html text
  flutter_html: ^3.0.0-alpha.6
  #to share
  share_plus: ^6.3.0
  # app guide
  showcaseview: ^2.0.0+1
  # intro 3rd slide
  widget_marquee: ^0.0.5
  # read more
  readmore: ^2.2.0


  #to change package name
  change_app_package_name: ^1.1.0

  #get current timezone name
  in_app_purchase: ^3.1.5
#  flutter_inapp_purchase: ^5.3.1

  #open url
#  crypto: ^3.0.2
#  open_file: ^3.2.1
#  flutter_widget_from_html: ^0.9.1

  dropdown_button2: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  fonts:

    - family: SF Pro Bold
      fonts:
        - asset: assets/fonts/sf_pro_display_bold.OTF
    - family: SF Pro Medium
      fonts:
        - asset: assets/fonts/sf_pro_display_medium.OTF
    - family: SF Pro Regular
      fonts:
        - asset: assets/fonts/sf_pro_display_regular.OTF
    - family: SF Pro SemiBold
      fonts:
        - asset: assets/fonts/sf_pro_display_semi_bold.OTF


  assets:
  - assets/images/
  - assets/icons/
  - assets/slide/
  - assets/resources/

